FROM node:21.6.0

RUN apt-get update && apt-get install -y \
    libnss3 \
    libnspr4 \
    libgbm1 \
    libx11-xcb1 \
    libxrandr2 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxfixes3 \
    libxi6 \
    libgtk-3-0 \
    libgdk-pixbuf2.0-0 \
    libatk1.0-0 \
    libasound2 \
    libdbus-1-3 \
    wget \
    xvfb \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /e2e

COPY apps/e2e .

RUN npm install

RUN npx playwright install

RUN chmod +x run-tests.sh

CMD ./run-tests.sh $TEST_TAG
